config/routes.rb
Rails.application.routes.draw do
  apipie
  devise_for :users

  root 'welcome#index'

  resources :users

  resources :devices do
    resources :intents, only: :index
    resources :device_apps, shallow: true
  end
  resources :device_types
  resources :apps
  resources :museums
  resources :power_controllers
  resources :power_controller_ports, only: [:edit, :update]

  post 'start_devices' => "command#start_command"
  post 'stop_devices'  => "command#stop_command"
  post 'broadcast_message' => "command#broadcast_message"
  post 'start_app' => "command#start_app"


  namespace :api do
    namespace :v1 do

      resources :users, only: [] do
        post :signin, on: :collection
      end

      resources :museums, only: :show do
        resources :devices, only: :index
      end
      
      resources :apps, only: [:index, :show]

      resource :command, only: [] do
        post :start_devices
        post :stop_devices
        post :broadcast_message
      end
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/power_controllers_controller.rb
class PowerControllersController < ApplicationController
  before_action :set_power_controller, only: [:show, :edit, :update, :destroy]

  # GET /power_controllers
  # GET /power_controllers.json
  def index
    @power_controllers = PowerController.all
  end

  # GET /power_controllers/1
  # GET /power_controllers/1.json
  def show
  end

  # GET /power_controllers/new
  def new
    @power_controller = PowerController.new
  end

  # GET /power_controllers/1/edit
  def edit
  end

  # POST /power_controllers
  # POST /power_controllers.json
  def create
    @power_controller = PowerController.new(power_controller_params)

    respond_to do |format|
      if PowerController.create_controller(@power_controller)
        format.html { redirect_to @power_controller, notice: 'Power controller was successfully created.' }
        format.json { render :show, status: :created, location: @power_controller }
      else
        format.html { render :new }
        format.json { render json: @power_controller.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /power_controllers/1
  # PATCH/PUT /power_controllers/1.json
  def update
    respond_to do |format|
      if @power_controller.update(power_controller_params)
        format.html { redirect_to @power_controller, notice: 'Power controller was successfully updated.' }
        format.json { render :show, status: :ok, location: @power_controller }
      else
        format.html { render :edit }
        format.json { render json: @power_controller.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /power_controllers/1
  # DELETE /power_controllers/1.json
  def destroy
    @power_controller.destroy
    respond_to do |format|
      format.html { redirect_to power_controllers_url, notice: 'Power controller was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_power_controller
      @power_controller = PowerController.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def power_controller_params
      params.require(:power_controller).permit(:pid, :name, :museum_id, :device_type, :address, :status, :note)
    end
end

app/views/power_controllers/_form.html.erb
<%= bootstrap_form_for(power_controller, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-10") do |form| %>
  <%= form.text_field :pid %>

  <%= form.text_field :name %>

  <%= form.select :museum_id, Museum.all.map{|m| [m.name, m.id] }, include_blank: true %>

  <%= form.select :device_type, PowerController.device_type.options %>

  <%= form.text_field :address %>

  <%= form.text_area :note %>

  <%= form.form_group do %>
        <%= form.primary %>
        <%= link_to '取消', power_controllers_path, class: 'btn btn-link' %>
  <% end %>
<% end %>

app/views/power_controllers/edit.html.erb
<h1>编辑控制器</h1>

<%= render 'form', power_controller: @power_controller %>

app/views/power_controllers/index.html.erb
<h1>控制器</h1>

<div class="m-b-10">
  <%= link_to '添加控制器', new_power_controller_path, class: "btn btn-default" %>
</div>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>唯一标示</th>
      <th>名称</th>
      <th>博物馆</th>
      <th>设备类型</th>
      <th>地址</th>
      <th>状态</th>
      <th>备注</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @power_controllers.each do |power_controller| %>
      <tr>
        <td><%= power_controller.pid %></td>
        <td><%= power_controller.name %></td>
        <td><%= link_to power_controller.museum.name, museum_path(power_controller.museum_id) %></td>
        <td><%= power_controller.device_type %></td>
        <td><%= power_controller.address %></td>
        <td><%= power_controller.status_text %></td>
        <td><%= power_controller.note %></td>
        <td><%= link_to '详情', power_controller %></td>
        <td><%= link_to '编辑', edit_power_controller_path(power_controller) %></td>
        <td><%= link_to '删除', power_controller, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/power_controllers/new.html.erb
<h1>添加控制器</h1>

<%= render 'form', power_controller: @power_controller %>

app/views/power_controllers/show.html.erb
<h3><span class="text-muted"><%= @power_controller.museum.name %>/</span> #<%= @power_controller.id %> <%= @power_controller.name %> </h3>

<table class="table">
  <thead>
  <tr>
    <th>唯一标示</th>
    <th>博物馆</th>
    <th>设备类型</th>
    <th>地址</th>
    <th>状态</th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td><%= @power_controller.pid %></td>
    <td><%= @power_controller.museum.name %></td>
    <td><%= @power_controller.device_type %></td>
    <td><%= @power_controller.address %></td>
    <td><%= @power_controller.status_text %></td>
  </tr>
  <tr>
    <th>备注</th>
    <td colspan="4"><%= @power_controller.note %></td>
  </tr>
  </tbody>
</table>

<h4>关联的设备</h4>

<ul class="list-inline">
  <% @power_controller.devices.each do |device| %>
    <li><%= link_to device.name, device_device_apps_path(device) %></li>
  <% end %>
</ul>

<h4>端口列表</h4>

<table class="table table-bordered">
  <thead>
  <tr>
    <th>端口</th>
    <th>状态</th>
    <!--
    <th>控制设备</th>
    -->
    <th>备注</th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @power_controller.ports.each do |port| %>
      <tr>
        <td><%= port.index + 1 %></td>
        <td><%= port.status_text %></td>
        <!--
        <td><%= link_to port.device.name, device_path(port.device) if port.device %></td>
        -->
        <td><%= port.note %></td>
        <td><%= link_to "编辑", edit_power_controller_port_path(port) %></td>
      </tr>
  <% end %>
  </tbody>
</table>