config/routes.rb
Rails.application.routes.draw do
  apipie
  devise_for :users

  root 'welcome#index'

  resources :users

  resources :devices do
    resources :intents, only: :index
    resources :device_apps, shallow: true
  end
  resources :device_types
  resources :apps
  resources :museums
  resources :power_controllers
  resources :power_controller_ports, only: [:edit, :update]

  post 'start_devices' => "command#start_command"
  post 'stop_devices'  => "command#stop_command"
  post 'broadcast_message' => "command#broadcast_message"
  post 'start_app' => "command#start_app"


  namespace :api do
    namespace :v1 do

      resources :users, only: [] do
        post :signin, on: :collection
      end

      resources :museums, only: :show do
        resources :devices, only: :index
      end
      
      resources :apps, only: [:index, :show]

      resource :command, only: [] do
        post :start_devices
        post :stop_devices
        post :broadcast_message
      end
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/device.rb
class Device < ApplicationRecord
  extend Enumerize

  belongs_to :device_type
  belongs_to :museum, optional: true
  has_many :device_apps, dependent: :destroy
  has_many :apps, through: :device_apps
  has_many :intents, dependent: :nullify
  belongs_to :current_status, optional: true, class_name: 'EventType', foreign_key: 'status'
  # TODO 要在 apps 里面
  belongs_to :default_app, class_name: 'App', optional: true

  belongs_to :power_controller, optional: true
  has_one :power_controller_port

  validates :name, :device_type_id, presence: true
  validates :name, uniqueness: { scope: :museum_id }
  validates :port_index, inclusion: { in: [1, 2] }, if: 'power_controller.present?'
  validate :validate_default_app, if: 'default_app_id.present?'

  enumerize :start_cmd, in: %w[NONE BOOT_MANUAL BOOT_AUTO BOOT_PROJECTOR], default: "NONE"
  enumerize :stop_cmd, in: %w[NONE SOFT_SHUTDOWN_PC SHUTDOWN_PC SHUTDOWN_PROJECTOR], default: "NONE"

  scope :active, -> { where(is_active: true) }


  def start_command
    case self.start_cmd
      when "BOOT_MANUAL" then
        if power_controller.present? && port_index.present?
          PowerControllerService.boot_manual(self.power_controller.pid, self.port_index)
        end
      when "BOOT_AUTO" then
        if power_controller.present? && port_index.present?
          PowerControllerService.boot_auto(self.power_controller.pid, self.port_index)
        end
      when "BOOT_PROJECTOR" then
        if power_controller.present?
          PowerControllerService.boot_projector(self.power_controller.pid)
        end
    end
  end

  def stop_command
    case self.stop_cmd
      when "SOFT_SHUTDOWN_PC" then
        PowerControllerService.soft_shutdown_pc(self.id)
      when "SHUTDOWN_PC" then
        if self.power_controller.present?
          PowerControllerService.shutdown_pc(self.id, self.power_controller.pid, self.port_index)
        end
      when "SHUTDOWN_PROJECTOR" then
        if self.power_controller.present?
          PowerControllerService.shutdown_projector(self.id, self.power_controller.pid)
        end
    end
  end

  def is_running?
    if current_status.present?
      current_status.id.in? [2, 4, 5, 6, 7]
    else
      false
    end
  end

  def is_off?
    if current_status.present?
      current_status.id.in? [1, 3]
    else
      true
    end
  end

  private
  def validate_default_app
    unless self.apps.map(&:id).include? default_app_id
      self.errors.add('default_app_id', "必须在设备应用中选择")
    end
  end
end

app/models/device_type.rb
class DeviceType < ApplicationRecord

  validates :name, presence: true, uniqueness: true
end

app/controllers/api/v1/devices_controller.rb
class Api::V1::DevicesController < Api::V1::BaseController


  api! "博物馆的设备列表"
  example <<-JSON
[
    {
        "id": 1,
        "name": "姜浩电脑",
        "type_name": "general",
        "type_id": 1,
        "museum_id": 1,
        "is_active": true,
        "app_id": null,
        "status": 1,
        "note": "",
        "address": "",
        "created_at": "2017-06-26T11:35:20.000+08:00",
        "apps": [
            {
                "id": 1,
                "name": "guanniao",
                "version": "v1.0.0",
                "note": "观鸟捕蝉图",
                "link": "http://0.0.0.0:3000/api/v1/apps/1.json"
            }
        ]
    }
]
  JSON
  def index
    @museum = Museum.find params[:museum_id]
    @devices = @museum.devices.active.order(:created_at)
  end

end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy]

  # GET /devices
  # GET /devices.json
  def index
    @devices = Device.all
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
  end

  # GET /devices/new
  def new
    @device = Device.new
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(device_params)
    @device.current_status = EventType.find_by(id: 1)

    respond_to do |format|
      if @device.save
        format.html { redirect_to devices_url, notice: 'Device was successfully created.' }
        format.json { render :show, status: :created, location: @device }
      else
        format.html { render :new }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to devices_url, notice: 'Device was successfully updated.' }
        format.json { render :show, status: :ok, location: @device }
      else
        format.html { render :edit }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to devices_url, notice: 'Device was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params.require(:device).permit(:name, :museum_id, :device_type_id, :address, :note, :is_active, :default_app_id, :power_controller_id, :port_index, :start_cmd, :stop_cmd)
    end
end

app/views/devices/_form.html.erb
<%= bootstrap_form_for(device, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-10") do |form| %>
    <%= form.text_field :name, id: :device_name %>

    <%= form.select :museum_id, Museum.all.map{|m| [m.name, m.id] }, include_blank: true %>

    <%= form.select :device_type_id, DeviceType.all.map{|d| [d.name, d.id] } %>

    <%= form.text_field :address, id: :device_address %>

    <%= form.collection_radio_buttons :is_active, [['使用', true], ['停用', false]], :last, :first %>

    <%= form.select :default_app_id, device.apps.all.map{|a| [a.full_name, a.id] }, include_blank: true %>

    <%= form.select :power_controller_id, PowerController.all.map{|p| [p.name, p.id] }, include_blank: true %>

    <%= form.select :port_index, [[1, 1], [2, 2]], include_blank: true %>

    <%= form.select :start_cmd, Device.start_cmd.options %>

    <%= form.select :stop_cmd, Device.stop_cmd.options %>

    <%= form.text_area :note, id: :device_note %>

    <%= form.form_group do %>
      <%= form.submit %>
    <% end %>
<% end %>

app/views/devices/_info.html.erb
<h3><span class="text-muted"><%= @device.museum.try(:name) %>/</span> #<%= @device.id %> <%= @device.name %> </h3>

<div class="m-v-20">
  <span>设备类型：</span><span><%= @device.device_type.name %></span>
  <span class="m-l-10">运行状态：</span><span><%= @device.current_status.try(:name) %></span>
  <span class="m-l-10">控制器：</span><span><%= link_to @device.power_controller.name, power_controller_path(@device.power_controller) if @device.power_controller.present? %></span>
  <span class="m-l-10">控制端口：</span><%= @device.port_index %>
  <span class="m-l-10">开机命令：</span><%= @device.start_cmd.text %>
  <span class="m-l-10">关机命令：</span><%= @device.stop_cmd.text %>

  <span class="m-l-10"><%= link_to "编辑", edit_device_path(@device) %></span>
</div>

app/views/devices/edit.html.erb
<h1>编辑设备</h1>

<%= render 'form', device: @device %>

app/views/devices/index.html.erb
<h1>设备</h1>

<div class="m-v-10">
<%= link_to '添加设备', new_device_path, class: 'btn btn-default' %>
<%= link_to '设备类型', device_types_path, class: 'btn btn-link' %>
</div>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>ID</th>
      <th>名称</th>
      <th>博物馆</th>
      <th>设备类型</th>
      <th>运行</th>
      <th>地址</th>
      <th>停用</th>
      <th>备注</th>
      <th>控制器</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @devices.each do |device| %>
      <tr class="<%= device.is_active ? '' : 'text-muted' %>">
        <td><%= device.id %></td>
        <td><%= link_to device.name, device_device_apps_path(device) %></td>
        <td><%= device.museum.try(:name) %></td>
        <td><%= device.device_type.name %></td>
        <td><%= device.current_status.try(:name) %></td>
        <td><%= device.address %></td>
        <td><%= device.is_active ? '正常' : '停用' %></td>
        <td><%= device.note %></td>
        <td><%= link_to device.power_controller.name, power_controller_path(device.power_controller_id) if device.power_controller %></td>
        <td><%= link_to '编辑', edit_device_path(device) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/devices/new.html.erb
<h1>添加设备</h1>

<%= render 'form', device: @device %>

app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @device.name %>
</p>

<p>
  <strong>Museum:</strong>
  <%= @device.museum_id %>
</p>

<p>
  <strong>Device type:</strong>
  <%= @device.device_type_id %>
</p>

<p>
  <strong>Address:</strong>
  <%= @device.address %>
</p>

<p>
  <strong>Is active:</strong>
  <%= @device.is_active %>
</p>

<p>
  <strong>Note:</strong>
  <%= @device.note %>
</p>

<%= link_to 'Edit', edit_device_path(@device) %> |
<%= link_to 'Back', devices_path %>