config/routes.rb
Rails.application.routes.draw do
  apipie
  devise_for :users

  root 'welcome#index'

  resources :users

  resources :devices do
    resources :intents, only: :index
    resources :device_apps, shallow: true
  end
  resources :device_types
  resources :apps
  resources :museums
  resources :power_controllers
  resources :power_controller_ports, only: [:edit, :update]

  post 'start_devices' => "command#start_command"
  post 'stop_devices'  => "command#stop_command"
  post 'broadcast_message' => "command#broadcast_message"
  post 'start_app' => "command#start_app"


  namespace :api do
    namespace :v1 do

      resources :users, only: [] do
        post :signin, on: :collection
      end

      resources :museums, only: :show do
        resources :devices, only: :index
      end
      
      resources :apps, only: [:index, :show]

      resource :command, only: [] do
        post :start_devices
        post :stop_devices
        post :broadcast_message
      end
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/device_types_controller.rb
class DeviceTypesController < ApplicationController
  before_action :set_device_type, only: [:show, :edit, :update, :destroy]

  # GET /device_types
  # GET /device_types.json
  def index
    @device_types = DeviceType.all
  end

  # GET /device_types/1
  # GET /device_types/1.json
  def show
  end

  # GET /device_types/new
  def new
    @device_type = DeviceType.new
  end

  # GET /device_types/1/edit
  def edit
  end

  # POST /device_types
  # POST /device_types.json
  def create
    @device_type = DeviceType.new(device_type_params)

    respond_to do |format|
      if @device_type.save
        format.html { redirect_to device_types_url, notice: 'Device type was successfully created.' }
        format.json { render :show, status: :created, location: @device_type }
      else
        format.html { render :new }
        format.json { render json: @device_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /device_types/1
  # PATCH/PUT /device_types/1.json
  def update
    respond_to do |format|
      if @device_type.update(device_type_params)
        format.html { redirect_to device_types_url, notice: 'Device type was successfully updated.' }
        format.json { render :show, status: :ok, location: @device_type }
      else
        format.html { render :edit }
        format.json { render json: @device_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /device_types/1
  # DELETE /device_types/1.json
  def destroy
    @device_type.destroy
    respond_to do |format|
      format.html { redirect_to device_types_url, notice: 'Device type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device_type
      @device_type = DeviceType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_type_params
      params.require(:device_type).permit(:name, :note)
    end
end

app/views/device_types/_form.html.erb
<%= bootstrap_form_for(device_type) do |form| %>

    <%= form.text_field :name, id: :device_type_name %>

    <%= form.text_area :note, id: :device_type_note %>

    <%= form.submit %>
<% end %>

app/views/device_types/edit.html.erb
<h1>编辑设备类型</h1>

<%= render 'form', device_type: @device_type %>

app/views/device_types/index.html.erb
<h1>设备类型</h1>
<%# link_to '添加设备类型', new_device_type_path, class: 'btn btn-default' %>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>ID</th>
      <th>名称</th>
      <th>备注</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @device_types.each do |device_type| %>
      <tr>
        <td><%= device_type.id %></td>
        <td><%= device_type.name %></td>
        <td><%= device_type.note %></td>
        <td><%# link_to '详情', device_type %></td>
        <td><%# link_to '编辑', edit_device_type_path(device_type) %></td>
        <td><%# link_to '删除', device_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/device_types/new.html.erb
<h1>添加设备类型</h1>

<%= render 'form', device_type: @device_type %>

app/views/device_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @device_type.name %>
</p>

<p>
  <strong>Note:</strong>
  <%= @device_type.note %>
</p>

<%= link_to 'Edit', edit_device_type_path(@device_type) %> |
<%= link_to 'Back', device_types_path %>