config/routes.rb
Rails.application.routes.draw do
  apipie
  devise_for :users

  root 'welcome#index'

  resources :users

  resources :devices do
    resources :intents, only: :index
    resources :device_apps, shallow: true
  end
  resources :device_types
  resources :apps
  resources :museums
  resources :power_controllers
  resources :power_controller_ports, only: [:edit, :update]

  post 'start_devices' => "command#start_command"
  post 'stop_devices'  => "command#stop_command"
  post 'broadcast_message' => "command#broadcast_message"
  post 'start_app' => "command#start_app"


  namespace :api do
    namespace :v1 do

      resources :users, only: [] do
        post :signin, on: :collection
      end

      resources :museums, only: :show do
        resources :devices, only: :index
      end
      
      resources :apps, only: [:index, :show]

      resource :command, only: [] do
        post :start_devices
        post :stop_devices
        post :broadcast_message
      end
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/device_app.rb
class DeviceApp < ApplicationRecord
  belongs_to :device
  belongs_to :app

  validates :device_id, :app_id, presence: true
  validates :app_id, uniqueness: { scope: :device_id }
end

app/controllers/device_apps_controller.rb
class DeviceAppsController < ApplicationController
  before_action :set_device, only: [:index, :new, :create, :update]
  before_action :set_device_app, only: [:show, :edit, :update, :destroy]

  # GET /device_apps
  # GET /device_apps.json
  def index
    @device = Device.find params[:device_id]
    @device_apps = @device.device_apps.all
  end

  # GET /device_apps/1
  # GET /device_apps/1.json
  def show
  end

  # GET /device_apps/new
  def new
    @device_app = DeviceApp.new(device: @device)
  end

  # GET /device_apps/1/edit
  def edit
  end

  # POST /device_apps
  # POST /device_apps.json
  def create
    @device_app = DeviceApp.new(device_app_params)

    respond_to do |format|
      if @device_app.save
        format.html { redirect_to device_device_apps_path(@device), notice: 'Device app was successfully created.' }
        format.json { render :show, status: :created, location: @device_app }
      else
        format.html { render :new }
        format.json { render json: @device_app.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /device_apps/1
  # PATCH/PUT /device_apps/1.json
  def update
    respond_to do |format|
      if @device_app.update(device_app_params)
        format.html { redirect_to device_device_apps_path(@device), notice: 'Device app was successfully updated.' }
        format.json { render :show, status: :ok, location: @device_app }
      else
        format.html { render :edit }
        format.json { render json: @device_app.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /device_apps/1
  # DELETE /device_apps/1.json
  def destroy
    @device = @device_app.device
    @device_app.destroy
    respond_to do |format|
      format.html { redirect_to device_device_apps_path(@device), notice: 'Device app was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_device
      @device = Device.find params[:device_id]
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_device_app
      @device_app = DeviceApp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_app_params
      params.require(:device_app).permit(:device_id, :app_id, :note)
    end
end

app/views/device_apps/_form.html.erb
<%= bootstrap_form_for([device, device_app]) do |form| %>

    <%= form.hidden_field :device_id %>

    <%= form.select :app_id, App.all.map{|a| [a.full_name, a.id]} %>

    <%= form.text_area :note, id: :device_app_note %>

    <%= form.submit %>
<% end %>

app/views/device_apps/edit.html.erb
<h1>编辑设备应用</h1>

<%= render 'form', device_app: @device_app %>

app/views/device_apps/index.html.erb
<%= render 'devices/info' %>

<ul class="nav nav-tabs" style="margin-bottom: 20px;">
  <li role="presentation"  class="active"><a href="<%= device_device_apps_path  @device %>">应用</a></li>
  <li role="presentation"><a href="<%= device_intents_path @device %>">事件</a></li>
</ul>

<%= link_to '添加应用', new_device_device_app_path(@device), class: 'btn btn-default' %>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>应用</th>
      <th>备注</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @device_apps.each do |device_app| %>
      <tr>
        <td><%= device_app.app.full_name %></td>
        <td><%= device_app.note %></td>
        <td><%= link_to '删除', device_app, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/device_apps/new.html.erb
<h1>给设备添加应用</h1>

<%= render 'form', device: @device, device_app: @device_app %>

app/views/device_apps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Device:</strong>
  <%= @device_app.device_id %>
</p>

<p>
  <strong>App:</strong>
  <%= @device_app.app_id %>
</p>

<p>
  <strong>Note:</strong>
  <%= @device_app.note %>
</p>

<%= link_to 'Edit', edit_device_app_path(@device_app) %> |
<%= link_to 'Back', device_apps_path %>